#ifndef ZEROCTRL_BSMAN_CLOSED_SHIM_H
#define ZEROCTRL_BSMAN_CLOSED_SHIM_H

#include <psptypes.h>

typedef struct {
    u32 leaf_addr;
    u32 leaf_end_addr;
    u32 hit_count_addr;
    u32 activation_leaf_addr;
    u32 activation_leaf_end_addr;
    u32 activation_resume_addr;
    u32 activation_hits_addr;
    u32 bsman_call_leaf_addr;
    u32 bsman_call_leaf_end_addr;
    u32 bsman_call_target_addr;
    u32 bsman_call_hits_addr;
    u32 trace_stage_addr;
    u32 bsman_call_ra_addr;
    u32 bsman_return_leaf_addr;
    u32 bsman_return_leaf_end_addr;
    u32 prefix_result_leaf_addr;
    u32 prefix_result_leaf_end_addr;
    u32 prefix_result_zero_addr;
    u32 prefix_result_nonzero_addr;
    u32 prefix_flag_leaf_addr;
    u32 prefix_flag_leaf_end_addr;
    u32 prefix_flag_zero_addr;
    u32 prefix_flag_nonzero_addr;
    u32 prefix_mask_leaf_addr;
    u32 prefix_mask_leaf_end_addr;
    u32 prefix_mask_equal_addr;
    u32 prefix_mask_unequal_addr;
    u32 prefix_mask_delay_value_addr;
    u32 prefix_path_mask_addr;
    u32 prefix_result_zero_hits_addr;
    u32 prefix_result_nonzero_hits_addr;
    u32 prefix_flag_zero_hits_addr;
    u32 prefix_flag_nonzero_hits_addr;
    u32 prefix_mask_equal_hits_addr;
    u32 prefix_mask_unequal_hits_addr;
    u32 prefix_paf_call_leaf_addr;
    u32 prefix_paf_call_leaf_end_addr;
    u32 prefix_paf_return_leaf_addr;
    u32 prefix_paf_return_leaf_end_addr;
    u32 prefix_paf_target_addr;
    u32 prefix_paf_ra_addr;
    u32 prefix_paf_compat_mode_addr;
    u32 prefix_paf_natural_result_addr;
    u32 prefix_paf_substitution_hits_addr;
    u32 prefix_paf_return_hits_addr;
    u32 post_path_mask_addr;
    u32 bsman_natural_result_addr;
    u32 bsman_compat_mode_addr;
    u32 bsman_substitution_hits_addr;
    u32 bsman_effective_result_addr;
    u32 bsman_return_hits_addr;
    u32 post_bs_branch_leaf_addr;
    u32 post_bs_branch_leaf_end_addr;
    u32 post_bs_zero_addr;
    u32 post_bs_nonzero_addr;
    u32 post_bs_zero_hits_addr;
    u32 post_bs_nonzero_hits_addr;
    u32 post_state_branch_leaf_addr;
    u32 post_state_branch_leaf_end_addr;
    u32 post_state_zero_addr;
    u32 post_state_nonzero_addr;
    u32 post_state_delay_value_addr;
    u32 post_state_zero_hits_addr;
    u32 post_state_nonzero_hits_addr;
    u32 post_paf_call_leaf_addr;
    u32 post_paf_call_leaf_end_addr;
    u32 post_paf_return_leaf_addr;
    u32 post_paf_return_leaf_end_addr;
    u32 post_paf_target_addr;
    u32 post_paf_call0_ra_addr;
    u32 post_paf_call1_ra_addr;
    u32 post_paf_saved_ra_addr;
    u32 post_paf_result0_addr;
    u32 post_paf_result1_addr;
    u32 post_paf_return0_hits_addr;
    u32 post_paf_return1_hits_addr;
    u32 post_vsh_call_leaf_addr;
    u32 post_vsh_call_leaf_end_addr;
    u32 post_vsh_return_leaf_addr;
    u32 post_vsh_return_leaf_end_addr;
    u32 post_vsh_target_addr;
    u32 post_vsh_saved_ra_addr;
    u32 post_vsh_natural_result_addr;
    u32 post_vsh_return_hits_addr;
    u32 post_paf_entry0_hits_addr;
    u32 post_paf_entry1_hits_addr;
    u32 post_vsh_entry_hits_addr;
} ZeroCtrlBSManClosedRegistration;

typedef char ZeroCtrlBSManClosedRegistration_size[
    sizeof(ZeroCtrlBSManClosedRegistration) == 348 ? 1 : -1];

#endif
